wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.6.10
    t:
      1:
      - 1
      4: 3.6.10
      5: 0.11.1
      8:
      - 1
      - 2
      - 5
batch_size:
  desc: null
  value: 32
epoches:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.01
